-- Tasarımını yaptığınız tabloları oluşturan sql ifadeleri buraya yazınız.
-- veri tiplerine, nullable olma durumuna, default değerine ve tablolar arası foreign key kullanımına dikkat.

-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."user"
(
    user_id smallint NOT NULL,
    name character varying NOT NULL,
    surname character varying NOT NULL,
    password character varying NOT NULL,
    email character varying NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.address
(
    address_id smallint NOT NULL,
    city character varying NOT NULL,
    neighborhood character varying NOT NULL,
    street character varying NOT NULL,
    "number" bigint NOT NULL,
    user_id smallint NOT NULL,
    PRIMARY KEY (address_id)
);

CREATE TABLE IF NOT EXISTS public.likes
(
    like_id smallint[] NOT NULL,
    product_id smallint[] NOT NULL,
    user_id smallint NOT NULL,
    PRIMARY KEY (like_id)
);

CREATE TABLE IF NOT EXISTS public.cart
(
    cart_id smallint NOT NULL,
    product_id smallint[] NOT NULL,
    user_id smallint NOT NULL,
    PRIMARY KEY (cart_id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    product_id smallint NOT NULL,
    product_name character varying NOT NULL,
    product_price integer NOT NULL,
    product_properties character varying NOT NULL,
    product_stock bigint NOT NULL,
    PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public."order"
(
    order_id smallint NOT NULL,
    user_id smallint NOT NULL,
    order_date date NOT NULL,
    total_price bigint NOT NULL,
    cart_id smallint NOT NULL,
    PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.categories
(
    category_id smallint NOT NULL,
    category_name character varying NOT NULL,
    PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS public.reviews
(
    review_id smallint NOT NULL,
    review_body character varying NOT NULL,
    review_date date NOT NULL,
    user_id smallint NOT NULL,
    product_id smallint[] NOT NULL,
    PRIMARY KEY (review_id)
);

CREATE TABLE IF NOT EXISTS public.product_categories
(
    product_cat_id smallint NOT NULL,
    product_id smallint NOT NULL,
    category_id smallint NOT NULL,
    PRIMARY KEY (product_cat_id)
);

ALTER TABLE IF EXISTS public.address
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.likes
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.cart
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.products
    ADD FOREIGN KEY (product_id)
    REFERENCES public.cart (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."order"
    ADD FOREIGN KEY (cart_id)
    REFERENCES public.cart (cart_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.reviews
    ADD FOREIGN KEY (product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.product_categories
    ADD FOREIGN KEY (product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.product_categories
    ADD FOREIGN KEY (category_id)
    REFERENCES public.categories (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;